# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79438215c49c8f538d02f1075f70a5e3d1afaa64ddca7b67d8029798ab2886e8d7bcc5a029fbbfc48887c94b7fc1361d34c7c77b1bc80de9276a1ab5999026fc

test:
  secret_key_base: 5f7cd5b18a88bdcbffa95a8aac1413eb5f0cddc712ee2d208fd526db4b86ec3bf158fc52c6bab6fdf94218704e14e65a2f112989b075a51029f1912e93ea79bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
